### ISSUE TITLE
Need Supplier for Product

### ISSUE THREAD

**Issue by willatkova** [willatkova/makerpos-usergroup#2]
It is not necessary for Category, Brand and Supplier for each product.  Only need Supplier.

**Comment by willatkova** [comment]
#### ToDo

- [x] Model
- [x] Python API
- [x] DB Table
- [x] Bloc
- [x] Import from Product Spreadsheet
- [x] Create Supplier if needed
- [x] Create ProductSupplierLink if needed
- [x] Upload to API
- [x] Download from API

**Comment by willatkova** [comment]
Ready for Testing
